### ISSUE TITLE
SE

### ISSUE THREAD

**Issue by skrackow** [helske/diagis#1]
weighted_se gives 0 for all na sample, ought to give na, I guess?!

**Comment by helske** [comment]
Thanks that makes sense, but can you give me minimal example as I can't reproduce this:
```
> diagis::weighted_se(c(NA, NA), w = c(1, 1))
Error in UseMethod("weighted_se", x) : 
  no applicable method for 'weighted_se' applied to an object of class "logical"
> diagis:::weighted_se.numeric(c(NA, NA), w=c(1, 1))
[1] NA
```

**Comment by skrackow** [comment]
U need to set na.rm=T

Jouni Helske <notifications@github.com> schrieb am So., 24. Mai 2020, 17:05:

**Comment by helske** [comment]
Of course, thanks, I see it now.

**Comment by helske** [comment]
Updated to Github, should work as expected now. Will update to CRAN ASAP as well.

**Comment by skrackow** [comment]
Tnx, SVEN.

Jouni Helske <notifications@github.com> schrieb am So., 24. Mai 2020, 17:39:
